/*
* Copyright (c) 2020 Radiometrics Inc.
*
*/

/** Generated by RAMADDA DatabaseManager */

package com.radiometrics.plugin;


import org.ramadda.util.sql.*;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;

import java.util.Date;


/**
 * Class description
 *
 *
 * @author         Enter your name here...    
 */
public class RdxInstrumentLog extends DbObject {

    /** _more_          */
    public static final String DB_TABLE_NAME = "rdx_instrument_log";

    /** _more_          */
    public static final String COL_ENTRY_ID = DB_TABLE_NAME + ".entry_id";

    /** _more_          */
    public static final String COL_NODOT_ENTRY_ID = "entry_id";

    /** _more_          */
    public static final String COL_DATE = DB_TABLE_NAME + ".date";

    /** _more_          */
    public static final String COL_NODOT_DATE = "date";

    /** _more_          */
    public static final String COL_INSTRUMENT_ID = DB_TABLE_NAME
                                                   + ".instrument_id";

    /** _more_          */
    public static final String COL_NODOT_INSTRUMENT_ID = "instrument_id";

    /** _more_          */
    public static final String COL_ELAPSED_NETWORK_MINUTES =
        DB_TABLE_NAME + ".elapsed_network_minutes";

    /** _more_          */
    public static final String COL_NODOT_ELAPSED_NETWORK_MINUTES =
        "elapsed_network_minutes";

    /** _more_          */
    public static final String COL_ELAPSED_DATA_MINUTES =
        DB_TABLE_NAME + ".elapsed_data_minutes";

    /** _more_          */
    public static final String COL_NODOT_ELAPSED_DATA_MINUTES =
        "elapsed_data_minutes";

    /** _more_          */
    public static final String COL_ELAPSED_LDM_MINUTES =
        DB_TABLE_NAME + ".elapsed_ldm_minutes";

    /** _more_          */
    public static final String COL_NODOT_ELAPSED_LDM_MINUTES =
        "elapsed_ldm_minutes";

    /** _more_          */
    public static final String[] ARRAY = new String[] {
        COL_ENTRY_ID, COL_DATE, COL_INSTRUMENT_ID,
        COL_ELAPSED_NETWORK_MINUTES, COL_ELAPSED_DATA_MINUTES,
        COL_ELAPSED_LDM_MINUTES
    };

    /** _more_          */
    public static final String COLUMNS = SqlUtil.comma(ARRAY);

    /** _more_          */
    public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);

    /** _more_          */
    public static final String INSERT =
        SqlUtil.makeInsert(DB_TABLE_NAME, NODOT_COLUMNS,
                           SqlUtil.getQuestionMarks(ARRAY.length));


    /** _more_          */
    private String entry_id;

    /** _more_          */
    private Date date;

    /** _more_          */
    private String instrument_id;

    /** _more_          */
    private int elapsed_network_minutes;

    /** _more_          */
    private int elapsed_data_minutes;

    /** _more_          */
    private int elapsed_ldm_minutes;


    /**
     * _more_
     *
     * @param results _more_
     *
     * @throws Exception _more_
     */
    public RdxInstrumentLog(ResultSet results) throws Exception {
        entry_id      = results.getString(COL_NODOT_ENTRY_ID);
        date          = getDate(results, COL_NODOT_DATE);
        instrument_id = results.getString(COL_NODOT_INSTRUMENT_ID);
        elapsed_network_minutes =
            results.getInt(COL_NODOT_ELAPSED_NETWORK_MINUTES);
        elapsed_data_minutes = results.getInt(COL_NODOT_ELAPSED_DATA_MINUTES);
        elapsed_ldm_minutes  = results.getInt(COL_NODOT_ELAPSED_LDM_MINUTES);
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getEntryId() {
        return entry_id;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setEntryId(String v) {
        entry_id = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public Date getDate() {
        return date;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setDate(Date v) {
        date = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getInstrumentId() {
        return instrument_id;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setInstrumentId(String v) {
        instrument_id = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getElapsedNetworkMinutes() {
        return elapsed_network_minutes;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setElapsedNetworkMinutes(int v) {
        elapsed_network_minutes = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getElapsedDataMinutes() {
        return elapsed_data_minutes;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setElapsedDataMinutes(int v) {
        elapsed_data_minutes = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getElapsedLdmMinutes() {
        return elapsed_ldm_minutes;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setElapsedLdmMinutes(int v) {
        elapsed_ldm_minutes = v;
    }



}
