/*
* Copyright (c) 2008-2019 Geode Systems LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*     http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/** Generated by RAMADDA DatabaseManager */

package com.radiometrics.plugin;


import org.ramadda.util.sql.*;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;

import java.util.Date;


/**
 * Class description
 *
 *
 * @version        $version$, Tue, Jun 16, '20
 * @author         Enter your name here...    
 */
public class RdxNotifications extends DbObject {

    /** _more_          */
    public static final String DB_TABLE_NAME = "rdx_notifications";

    /** _more_          */
    public static final String COL_ENTRY_ID = DB_TABLE_NAME + ".entry_id";

    /** _more_          */
    public static final String COL_NODOT_ENTRY_ID = "entry_id";

    /** _more_          */
    public static final String COL_START_DATE = DB_TABLE_NAME + ".start_date";

    /** _more_          */
    public static final String COL_NODOT_START_DATE = "start_date";

    /** _more_          */
    public static final String COL_LAST_MESSAGE_DATE = DB_TABLE_NAME
                                                       + ".last_message_date";

    /** _more_          */
    public static final String COL_NODOT_LAST_MESSAGE_DATE =
        "last_message_date";

    /** _more_          */
    public static final String COL_SEND_TO = DB_TABLE_NAME + ".send_to";

    /** _more_          */
    public static final String COL_NODOT_SEND_TO = "send_to";

    /** _more_          */
    public static final String COL_NUMBER_EMAILS = DB_TABLE_NAME
                                                   + ".number_emails";

    /** _more_          */
    public static final String COL_NODOT_NUMBER_EMAILS = "number_emails";

    /** _more_          */
    public static final String COL_NUMBER_SMS = DB_TABLE_NAME + ".number_sms";

    /** _more_          */
    public static final String COL_NODOT_NUMBER_SMS = "number_sms";

    /** _more_          */
    public static final String[] ARRAY = new String[] {
        COL_ENTRY_ID, COL_START_DATE, COL_LAST_MESSAGE_DATE, COL_SEND_TO,
        COL_NUMBER_EMAILS, COL_NUMBER_SMS
    };

    /** _more_          */
    public static final String COLUMNS = SqlUtil.comma(ARRAY);

    /** _more_          */
    public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);

    /** _more_          */
    public static final String INSERT =
        SqlUtil.makeInsert(DB_TABLE_NAME, NODOT_COLUMNS,
                           SqlUtil.getQuestionMarks(ARRAY.length));


    /** _more_          */
    private String entry_id;

    /** _more_          */
    private Date start_date;

    /** _more_          */
    private Date last_message_date;

    /** _more_          */
    private String send_to;

    /** _more_          */
    private int number_emails;

    /** _more_          */
    private int number_sms;


    /**
     * _more_
     *
     * @param results _more_
     *
     * @throws Exception _more_
     */
    public RdxNotifications(ResultSet results) throws Exception {
        entry_id          = results.getString(COL_NODOT_ENTRY_ID);
        start_date        = getDate(results, COL_NODOT_START_DATE);
        last_message_date = getDate(results, COL_NODOT_LAST_MESSAGE_DATE);
        send_to           = results.getString(COL_NODOT_SEND_TO);
        number_emails     = results.getInt(COL_NODOT_NUMBER_EMAILS);
        number_sms        = results.getInt(COL_NODOT_NUMBER_SMS);
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getEntryId() {
        return entry_id;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setEntryId(String v) {
        entry_id = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public Date getStartDate() {
        return start_date;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setStartDate(Date v) {
        start_date = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public Date getLastMessageDate() {
        return last_message_date;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setLastMessageDate(Date v) {
        last_message_date = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getSendTo() {
        return send_to;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setSendTo(String v) {
        send_to = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getNumberEmails() {
        return number_emails;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setNumberEmails(int v) {
        number_emails = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getNumberSms() {
        return number_sms;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setNumberSms(int v) {
        number_sms = v;
    }



}
