/**Generated by RAMADDA DatabaseManager**/

package com.radiometrics.plugin;

import org.ramadda.util.sql.*;
import java.util.Date;
import java.sql.Timestamp;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;

public class RdxNotifications extends DbObject {
    public static final String DB_TABLE_NAME = "rdx_notifications";
    public static final String COL_ENTRY_ID =  DB_TABLE_NAME + ".entry_id";
    public static final String COL_NODOT_ENTRY_ID =   "entry_id";
    public static final String COL_START_DATE =  DB_TABLE_NAME + ".start_date";
    public static final String COL_NODOT_START_DATE =   "start_date";
    public static final String COL_LAST_MESSAGE_DATE =  DB_TABLE_NAME + ".last_message_date";
    public static final String COL_NODOT_LAST_MESSAGE_DATE =   "last_message_date";
    public static final String COL_SEND_TO =  DB_TABLE_NAME + ".send_to";
    public static final String COL_NODOT_SEND_TO =   "send_to";
    public static final String COL_NUMBER_EMAILS =  DB_TABLE_NAME + ".number_emails";
    public static final String COL_NODOT_NUMBER_EMAILS =   "number_emails";
    public static final String COL_NUMBER_SMS =  DB_TABLE_NAME + ".number_sms";
    public static final String COL_NODOT_NUMBER_SMS =   "number_sms";
    public static final String[] ARRAY = new String[] {
        COL_ENTRY_ID,COL_START_DATE,COL_LAST_MESSAGE_DATE,COL_SEND_TO,COL_NUMBER_EMAILS,COL_NUMBER_SMS
    };
    public static final String COLUMNS = SqlUtil.comma(ARRAY);
    public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);
    public static final String INSERT =SqlUtil.makeInsert(DB_TABLE_NAME, NODOT_COLUMNS,SqlUtil.getQuestionMarks(ARRAY.length));


    private String entry_id;
    private Date start_date;
    private Date last_message_date;
    private String send_to;
    private int number_emails;
    private int number_sms;


    public RdxNotifications(ResultSet results) throws Exception {
        entry_id=results.getString(COL_NODOT_ENTRY_ID);
        start_date=getDate(results,COL_NODOT_START_DATE);
        last_message_date=getDate(results,COL_NODOT_LAST_MESSAGE_DATE);
        send_to=results.getString(COL_NODOT_SEND_TO);
        number_emails=results.getInt(COL_NODOT_NUMBER_EMAILS);
        number_sms=results.getInt(COL_NODOT_NUMBER_SMS);
    }

    public String getEntryId(){return entry_id;}
    public void  setEntryId(String v){entry_id=v;}

    public Date getStartDate(){return start_date;}
    public void  setStartDate(Date v){start_date=v;}

    public Date getLastMessageDate(){return last_message_date;}
    public void  setLastMessageDate(Date v){last_message_date=v;}

    public String getSendTo(){return send_to;}
    public void  setSendTo(String v){send_to=v;}

    public int getNumberEmails(){return number_emails;}
    public void  setNumberEmails(int v){number_emails=v;}

    public int getNumberSms(){return number_sms;}
    public void  setNumberSms(int v){number_sms=v;}



}

