/*
* Copyright (c) 2008-2019 Geode Systems LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*     http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

/** Generated by RAMADDA DatabaseManager */

package com.radiometrics.plugin;


import org.ramadda.util.sql.SqlUtil;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;

import java.util.Date;


/**
 * Class description
 *
 *
 * @version        $version$, Wed, Jun 10, '20
 * @author         Enter your name here...    
 */
public class RdxNotifications {

    /** _more_          */
    public static final String DB_TABLE_NAME = "rdx_notifications";

    /** _more_          */
    public static final String COL_ENTRY_ID = DB_TABLE_NAME + ".entry_id";

    /** _more_          */
    public static final String COL_NODOT_ENTRY_ID = "entry_id";

    /** _more_          */
    public static final String COL_EVENT_TYPE = DB_TABLE_NAME + ".event_type";

    /** _more_          */
    public static final String COL_NODOT_EVENT_TYPE = "event_type";

    /** _more_          */
    public static final String COL_DATE = DB_TABLE_NAME + ".date";

    /** _more_          */
    public static final String COL_NODOT_DATE = "date";

    /** _more_          */
    public static final String COL_TESTINT = DB_TABLE_NAME + ".testint";

    /** _more_          */
    public static final String COL_NODOT_TESTINT = "testint";

    /** _more_          */
    public static final String COL_TESTDOUBLE = DB_TABLE_NAME + ".testdouble";

    /** _more_          */
    public static final String COL_NODOT_TESTDOUBLE = "testdouble";

    /** _more_          */
    public static final String[] ARRAY = new String[] { COL_ENTRY_ID,
            COL_EVENT_TYPE, COL_DATE, COL_TESTINT, COL_TESTDOUBLE };

    /** _more_          */
    public static final String COLUMNS = SqlUtil.comma(ARRAY);

    /** _more_          */
    public static final String NODOT_COLUMNS = SqlUtil.commaNoDot(ARRAY);

    /** _more_          */
    public static final String INSERT =
        SqlUtil.makeInsert(DB_TABLE_NAME, NODOT_COLUMNS,
                           SqlUtil.getQuestionMarks(ARRAY.length));


    /** _more_          */
    private String entry_id;

    /** _more_          */
    private String event_type;

    /** _more_          */
    private Date date;

    /** _more_          */
    private int testint;

    /** _more_          */
    private double testdouble;


    /**
     * _more_
     *
     * @param results _more_
     *
     * @throws Exception _more_
     */
    public RdxNotifications(ResultSet results) throws Exception {
        entry_id   = results.getString(COL_NODOT_ENTRY_ID);
        event_type = results.getString(COL_NODOT_EVENT_TYPE);
        Timestamp date_ts = results.getTimestamp(COL_NODOT_DATE);
        if (date_ts != null) {
            date = new Date(date_ts.getTime());
        }
        testint    = results.getInt(COL_NODOT_TESTINT);
        testdouble = results.getDouble(COL_NODOT_TESTDOUBLE);
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getEntryId() {
        return entry_id;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setEntryId(String v) {
        entry_id = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public String getEventType() {
        return event_type;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setEventType(String v) {
        event_type = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public Date getDate() {
        return date;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setDate(Date v) {
        date = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public int getTestint() {
        return testint;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setTestint(int v) {
        testint = v;
    }

    /**
     * _more_
     *
     * @return _more_
     */
    public double getTestdouble() {
        return testdouble;
    }

    /**
     * _more_
     *
     * @param v _more_
     */
    public void setTestdouble(double v) {
        testdouble = v;
    }



}
